/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: notify.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "notify.pb-c.h"
void   notify__init
                     (Notify         *message)
{
  static Notify init_value = NOTIFY__INIT;
  *message = init_value;
}
size_t notify__get_packed_size
                     (const Notify *message)
{
  assert(message->base.descriptor == &notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify__pack
                     (const Notify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify__pack_to_buffer
                     (const Notify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Notify *
       notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Notify *)
     protobuf_c_message_unpack (&notify__descriptor,
                                allocator, len, data);
}
void   notify__free_unpacked
                     (Notify *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notifies__init
                     (Notifies         *message)
{
  static Notifies init_value = NOTIFIES__INIT;
  *message = init_value;
}
size_t notifies__get_packed_size
                     (const Notifies *message)
{
  assert(message->base.descriptor == &notifies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notifies__pack
                     (const Notifies *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notifies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notifies__pack_to_buffer
                     (const Notifies *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notifies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Notifies *
       notifies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Notifies *)
     protobuf_c_message_unpack (&notifies__descriptor,
                                allocator, len, data);
}
void   notifies__free_unpacked
                     (Notifies *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &notifies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor notify__field_descriptors[5] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Notify, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Notify, has_device),
    offsetof(Notify, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Notify, header),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Notify, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Notify, comment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify__field_indices_by_name[] = {
  0,   /* field[0] = ID */
  4,   /* field[4] = comment */
  3,   /* field[3] = content */
  1,   /* field[1] = device */
  2,   /* field[2] = header */
};
static const ProtobufCIntRange notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Notify",
  "Notify",
  "Notify",
  "",
  sizeof(Notify),
  5,
  notify__field_descriptors,
  notify__field_indices_by_name,
  1,  notify__number_ranges,
  (ProtobufCMessageInit) notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor notifies__field_descriptors[1] =
{
  {
    "notifies",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Notifies, n_notifies),
    offsetof(Notifies, notifies),
    &notify__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notifies__field_indices_by_name[] = {
  0,   /* field[0] = notifies */
};
static const ProtobufCIntRange notifies__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor notifies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Notifies",
  "Notifies",
  "Notifies",
  "",
  sizeof(Notifies),
  1,
  notifies__field_descriptors,
  notifies__field_indices_by_name,
  1,  notifies__number_ranges,
  (ProtobufCMessageInit) notifies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
